                .global print_int
                .equ    print_int_args, 1

                .bss
integer_buffer: .space  12

                .text
                # print_int(value): write signed decimal digits without a terminator.
                # the demos reuse this buffer between calls.
print_int:
                la      a1, integer_buffer
                addi    a1, a1, 12
                li      a2, 0
                li      t0, 10
                li      t2, 1
                sltz    t3, a0
                bgez    a0, 1f
                neg     a0, a0

                # extract the magnitude from right to left, including zero.
1:              beqz    t2, 3f
                remu    t1, a0, t0
                addi    t1, t1, '0'
                addi    a1, a1, -1
                sb      t1, (a1)
                addi    a2, a2, 1
                divu    a0, a0, t0
                mv      t2, a0
                j       1b

                # prepend a minus sign and write exactly the generated bytes.
3:              beqz    t3, 2f
                addi    a1, a1, -1
                li      t1, '-'
                sb      t1, (a1)
                addi    a2, a2, 1
2:              li      a0, 1
                li      a7, 64
                ecall
                ret
