                .global print_int
                .equ    print_int_args, 1
                .data
integer_buffer:
                .space  12
                .text
                # print_int(value): write signed decimal digits without a terminator.
                # The single-threaded demos reuse this buffer between calls.
print_int:
                la      a1, integer_buffer
                addi    a1, a1, 12
                li      a2, 0
                li      t0, 10
                li      t2, 1
                sltz    t3, a0
                bgez    a0, 1f
                neg     a0, a0
1:
                # Extract the magnitude from right to left, including zero.
                beqz    t2, 3f
                remu    t1, a0, t0
                addi    t1, t1, '0'
                addi    a1, a1, -1
                sb      t1, (a1)
                addi    a2, a2, 1
                divu    a0, a0, t0
                mv      t2, a0
                j       1b
3:

                # Prepend a minus sign and write exactly the generated bytes.
                beqz    t3, 2f
                addi    a1, a1, -1
                li      t1, '-'
                sb      t1, (a1)
                addi    a2, a2, 1
2:
                li      a0, 1
                li      a7, 64
                ecall
                ret


                .global print_array
                .equ    print_array_args, 2
                .data
array_open:
                .ascii "["
                .equ    array_open_len, (. - array_open)
array_separator:
                .ascii ", "
                .equ    array_separator_len, (. - array_separator)
array_close:
                .ascii "]\n"
                .equ    array_close_len, (. - array_close)
                .text
                # print_array(bytes, count): print signed bytes in index order.
print_array:
                # Preserve the cursor and remaining count across integer printing.
                addi    sp, sp, -16
                sw      s0, 0(sp)
                sw      s1, 4(sp)
                sw      ra, 12(sp)
                mv      s0, a0
                mv      s1, a1
                li      a0, 1
                la      a1, array_open
                li      a2, array_open_len
                li      a7, 64
                ecall

                # Each trip prints one value, with separators between values only.
1:
                beqz    s1, 3f
                lb      a0, (s0)
                jal     print_int
                addi    s0, s0, 1
                addi    s1, s1, -1
                beqz    s1, 2f
                li      a0, 1
                la      a1, array_separator
                li      a2, array_separator_len
                li      a7, 64
                ecall
2:
                j       1b
3:
                li      a0, 1
                la      a1, array_close
                li      a2, array_close_len
                li      a7, 64
                ecall

                # Restore the caller's frame in the same order as the saves.
                lw      s0, 0(sp)
                lw      s1, 4(sp)
                lw      ra, 12(sp)
                addi    sp, sp, 16
                ret
